import React, { useState, useEffect } from 'react';
import { generateRewindAlternatives } from '../services/geminiService';
import { Conflict } from '../types';
import { X, RefreshCw, CheckCircle, ArrowRight } from 'lucide-react';

interface RewindModalProps {
  conflict: Conflict;
  context: string[]; // surrounding messages
  onClose: () => void;
}

export const RewindModal: React.FC<RewindModalProps> = ({ conflict, context, onClose }) => {
  const [alternatives, setAlternatives] = useState<Conflict['alternatives']>([]);
  const [loading, setLoading] = useState(true);
  const [selectedAlt, setSelectedAlt] = useState<number | null>(null);

  useEffect(() => {
    const fetchAlternatives = async () => {
      setLoading(true);
      const results = await generateRewindAlternatives(conflict, context);
      setAlternatives(results);
      setLoading(false);
    };
    fetchAlternatives();
  }, [conflict, context]);

  return (
    <div className="fixed inset-0 bg-black/50 backdrop-blur-sm flex items-center justify-center z-50 p-4">
      <div className="bg-white rounded-2xl shadow-2xl max-w-2xl w-full flex flex-col max-h-[90vh]">
        {/* Header */}
        <div className="p-6 border-b border-gray-100 flex justify-between items-start">
          <div>
            <div className="flex items-center gap-2 mb-1">
              <span className="bg-red-100 text-red-600 px-2 py-0.5 rounded text-xs font-bold uppercase tracking-wider">
                Conflict Detected
              </span>
              <span className="text-gray-400 text-sm">Rewind Engine</span>
            </div>
            <h2 className="text-2xl font-bold text-gray-900">Argument Rewind</h2>
            <p className="text-gray-500 mt-1">{conflict.description}</p>
          </div>
          <button onClick={onClose} className="text-gray-400 hover:text-gray-600">
            <X size={24} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6 overflow-y-auto">
          {/* The Original Mistake */}
          <div className="mb-8 relative">
            <div className="absolute left-4 top-0 bottom-0 w-0.5 bg-gray-200"></div>
            <div className="pl-8 pb-4">
              <p className="text-xs font-semibold text-gray-500 mb-1">WHAT WAS SAID</p>
              <div className="bg-red-50 border border-red-100 p-4 rounded-xl relative">
                <p className="text-gray-800 italic">"{conflict.triggerMessage}"</p>
                <div className="absolute -left-[38px] top-1/2 -translate-y-1/2 w-4 h-4 rounded-full bg-red-500 border-4 border-white shadow-sm"></div>
              </div>
            </div>
          </div>

          {/* Alternatives */}
          <div>
            <div className="flex items-center justify-between mb-4">
              <p className="text-xs font-semibold text-gray-500 uppercase">Better Alternatives (Generated by Gemini)</p>
              {loading && <RefreshCw className="animate-spin text-brand-500" size={16} />}
            </div>

            <div className="space-y-4">
              {loading ? (
                // Skeletons
                [1, 2, 3].map(i => (
                  <div key={i} className="h-24 bg-gray-50 rounded-xl animate-pulse"></div>
                ))
              ) : (
                alternatives?.map((alt, idx) => (
                  <div 
                    key={idx}
                    onClick={() => setSelectedAlt(idx)}
                    className={`cursor-pointer group p-4 rounded-xl border-2 transition-all ${
                      selectedAlt === idx 
                        ? 'border-brand-500 bg-brand-50' 
                        : 'border-transparent bg-gray-50 hover:bg-gray-100 hover:border-gray-200'
                    }`}
                  >
                    <div className="flex justify-between items-start mb-2">
                      <span className={`px-2 py-0.5 rounded text-xs font-medium ${
                        alt.tone === 'Empathetic' ? 'bg-purple-100 text-purple-700' :
                        alt.tone === 'Assertive' ? 'bg-blue-100 text-blue-700' :
                        'bg-green-100 text-green-700'
                      }`}>
                        {alt.tone}
                      </span>
                      {selectedAlt === idx && <CheckCircle size={18} className="text-brand-600" />}
                    </div>
                    <p className="text-gray-800 font-medium mb-2">"{alt.text}"</p>
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <span className="font-semibold text-brand-600">Prediction:</span>
                      {alt.predictedOutcome}
                    </div>
                  </div>
                ))
              )}
            </div>
          </div>
        </div>

        {/* Footer */}
        <div className="p-6 border-t border-gray-100 bg-gray-50 rounded-b-2xl flex justify-end">
          <button 
            onClick={onClose}
            className="px-6 py-2 bg-white border border-gray-200 text-gray-700 rounded-lg hover:bg-gray-50 font-medium mr-3"
          >
            Cancel
          </button>
          <button 
            disabled={selectedAlt === null}
            onClick={onClose} // In a real app this would save or copy
            className="px-6 py-2 bg-brand-600 text-white rounded-lg hover:bg-brand-500 font-medium shadow-md shadow-brand-200 disabled:opacity-50 flex items-center gap-2"
          >
            Apply Fix <ArrowRight size={16} />
          </button>
        </div>
      </div>
    </div>
  );
};
